add_header Strict-Transport-Security 'max-age={{env "MAX_AGE"}}; includeSubDomains; preload';
add_header Expect-CT 'max-age=60, report-uri="https://domain.com/owasp/report"';
#add_header X-XSS-Protection "1; mode=block";
#add_header X-Content-Type-Options nosniff;
# Security headers
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-XSS-Protection "1; mode=block" always;