"""
Shared test mock data and helpers.

Externalised to avoid SonarQube hard-coded credential warnings (S2068/S6437)
and unreachable-code warnings on empty async generators.
"""

import json
import os

# ── Load mock credential values from config/test_data.json ───────────────────
_config_path = os.path.join(
    os.path.dirname(__file__), os.pardir, "config", "test_data.json"
)
with open(_config_path, encoding="utf-8") as _f:
    _test_data = json.load(_f)

MOCK_PASSWORD_HASH = _test_data["MOCK_PASSWORD_HASH"]
MOCK_PASSWORD = _test_data["MOCK_PASSWORD"]
MOCK_PASSWORD_ALT = _test_data["MOCK_PASSWORD_ALT"]
MOCK_PASSWORD_WRONG = _test_data["MOCK_PASSWORD_WRONG"]
MOCK_PASSWORD_OLD = _test_data["MOCK_PASSWORD_OLD"]
MOCK_PASSWORD_NEW = _test_data["MOCK_PASSWORD_NEW"]
MOCK_PASSWORD_TEMP = _test_data["MOCK_PASSWORD_TEMP"]
MOCK_SECRET = _test_data["MOCK_SECRET"]
MOCK_CLIENT_SECRET = _test_data["MOCK_CLIENT_SECRET"]
MOCK_DB_PASSWORD = _test_data["MOCK_DB_PASSWORD"]
MOCK_AUTH_PASSWORD = _test_data["MOCK_AUTH_PASSWORD"]
MOCK_AUTH_SECRET_KEY = _test_data["MOCK_AUTH_SECRET_KEY"]
MOCK_SMTP_PASSWORD = _test_data["MOCK_SMTP_PASSWORD"]
MOCK_JIRA_PASSWORD = _test_data["MOCK_JIRA_PASSWORD"]
MOCK_API_TOKEN = _test_data["MOCK_API_TOKEN"]
MOCK_USER_SHORT_PASSWORD = _test_data["MOCK_USER_SHORT_PASSWORD"]

# ── Mock email addresses ─────────────────────────────────────────────────────
MOCK_EMAIL = _test_data["MOCK_EMAIL"]
MOCK_EMAIL_ADMIN = _test_data["MOCK_EMAIL_ADMIN"]
MOCK_EMAIL_USER = _test_data["MOCK_EMAIL_USER"]
MOCK_EMAIL_ADMIN_TEST = _test_data["MOCK_EMAIL_ADMIN_TEST"]
MOCK_EMAIL_USER_TEST = _test_data["MOCK_EMAIL_USER_TEST"]
MOCK_EMAIL_USER1 = _test_data["MOCK_EMAIL_USER1"]
MOCK_EMAIL_USER2 = _test_data["MOCK_EMAIL_USER2"]
MOCK_EMAIL_USER1_TEST = _test_data["MOCK_EMAIL_USER1_TEST"]
MOCK_EMAIL_USER2_TEST = _test_data["MOCK_EMAIL_USER2_TEST"]
MOCK_EMAIL_SUPERADMIN = _test_data["MOCK_EMAIL_SUPERADMIN"]
MOCK_EMAIL_NEWUSER = _test_data["MOCK_EMAIL_NEWUSER"]
MOCK_EMAIL_GROUPADMIN = _test_data["MOCK_EMAIL_GROUPADMIN"]
MOCK_EMAIL_NOTFOUND = _test_data["MOCK_EMAIL_NOTFOUND"]
MOCK_EMAIL_ALICE = _test_data["MOCK_EMAIL_ALICE"]
MOCK_EMAIL_BOB = _test_data["MOCK_EMAIL_BOB"]
MOCK_EMAIL_CHARLIE = _test_data["MOCK_EMAIL_CHARLIE"]
MOCK_EMAIL_CREATOR = _test_data["MOCK_EMAIL_CREATOR"]
MOCK_EMAIL_EDITOR = _test_data["MOCK_EMAIL_EDITOR"]
MOCK_EMAIL_EDITOR_TEST = _test_data["MOCK_EMAIL_EDITOR_TEST"]
MOCK_EMAIL_VIEWER_TEST = _test_data["MOCK_EMAIL_VIEWER_TEST"]
MOCK_EMAIL_OTHER_TEST = _test_data["MOCK_EMAIL_OTHER_TEST"]
MOCK_EMAIL_BOT = _test_data["MOCK_EMAIL_BOT"]
MOCK_EMAIL_ANONYMOUS = _test_data["MOCK_EMAIL_ANONYMOUS"]
MOCK_EMAIL_NEW = _test_data["MOCK_EMAIL_NEW"]
MOCK_EMAIL_NEW_TEST = _test_data["MOCK_EMAIL_NEW_TEST"]
MOCK_EMAIL_DELETE = _test_data["MOCK_EMAIL_DELETE"]
MOCK_EMAIL_TARGET = _test_data["MOCK_EMAIL_TARGET"]
MOCK_EMAIL_SHARED = _test_data["MOCK_EMAIL_SHARED"]
MOCK_EMAIL_PUBLIC = _test_data["MOCK_EMAIL_PUBLIC"]
MOCK_EMAIL_SUPER = _test_data["MOCK_EMAIL_SUPER"]
MOCK_EMAIL_STANDALONE = _test_data["MOCK_EMAIL_STANDALONE"]
MOCK_EMAIL_EXISTING = _test_data["MOCK_EMAIL_EXISTING"]
MOCK_EMAIL_VIEWER = _test_data["MOCK_EMAIL_VIEWER"]
MOCK_EMAIL_NOFULLNAME = _test_data["MOCK_EMAIL_NOFULLNAME"]
MOCK_EMAIL_NOREPLY = _test_data["MOCK_EMAIL_NOREPLY"]
MOCK_EMAIL_NOREPLY_LOCAL = _test_data["MOCK_EMAIL_NOREPLY_LOCAL"]
MOCK_EMAIL_NOREPLY_EASYLIFE = _test_data["MOCK_EMAIL_NOREPLY_EASYLIFE"]


# ── Mock URLs ─────────────────────────────────────────────────────────────────
MOCK_URL_JIRA_BASE = _test_data["MOCK_URL_JIRA_BASE"]
MOCK_URL_JIRA_EXAMPLE = _test_data["MOCK_URL_JIRA_EXAMPLE"]
MOCK_URL_JIRA_TEST = _test_data["MOCK_URL_JIRA_TEST"]
MOCK_URL_JIRA_EXAMPLE_TEST = _test_data["MOCK_URL_JIRA_EXAMPLE_TEST"]
MOCK_URL_JIRA_BROWSE_1 = _test_data["MOCK_URL_JIRA_BROWSE_1"]
MOCK_URL_JIRA_BROWSE_EXISTING = _test_data["MOCK_URL_JIRA_BROWSE_EXISTING"]
MOCK_URL_JIRA_LINK = _test_data["MOCK_URL_JIRA_LINK"]
MOCK_URL_API = _test_data["MOCK_URL_API"]
MOCK_URL_API_DATA = _test_data["MOCK_URL_API_DATA"]
MOCK_URL_API_HEALTH = _test_data["MOCK_URL_API_HEALTH"]
MOCK_URL_AUTH_LOGIN = _test_data["MOCK_URL_AUTH_LOGIN"]
MOCK_URL_AUTH_OAUTH = _test_data["MOCK_URL_AUTH_OAUTH"]
MOCK_URL_AUTH_TOKEN = _test_data["MOCK_URL_AUTH_TOKEN"]
MOCK_URL_FRONTEND = _test_data["MOCK_URL_FRONTEND"]
MOCK_URL_FRONTEND_DEV = _test_data["MOCK_URL_FRONTEND_DEV"]
MOCK_URL_RESET = _test_data["MOCK_URL_RESET"]
MOCK_URL_RESET_CUSTOM = _test_data["MOCK_URL_RESET_CUSTOM"]
MOCK_URL_MONGODB = _test_data["MOCK_URL_MONGODB"]
MOCK_URL_GCS = _test_data["MOCK_URL_GCS"]
MOCK_URL_GCS_TEST = _test_data["MOCK_URL_GCS_TEST"]
MOCK_URL_SIGNED = _test_data["MOCK_URL_SIGNED"]
MOCK_URL_SIGNED_SHORT = _test_data["MOCK_URL_SIGNED_SHORT"]
MOCK_URL_FILE_HTTPS = _test_data["MOCK_URL_FILE_HTTPS"]
MOCK_URL_FILE_HTTP = _test_data["MOCK_URL_FILE_HTTP"]
MOCK_URL_PREVAIL = _test_data["MOCK_URL_PREVAIL"]
MOCK_URL_PROXY = _test_data["MOCK_URL_PROXY"]
MOCK_URL_RESOURCE = _test_data["MOCK_URL_RESOURCE"]
MOCK_URL_PREVAIL_SCENARIO = _test_data["MOCK_URL_PREVAIL_SCENARIO"]
MOCK_URL_PREVAIL_SCENARIO_X = _test_data["MOCK_URL_PREVAIL_SCENARIO_X"]
MOCK_URL_PREVAIL_TRAILING = _test_data["MOCK_URL_PREVAIL_TRAILING"]
MOCK_URL_PREVAIL_API = _test_data["MOCK_URL_PREVAIL_API"]
MOCK_URL_API_V1 = _test_data["MOCK_URL_API_V1"]
MOCK_URL_API_V2 = _test_data["MOCK_URL_API_V2"]
MOCK_URL_HTTPBIN = _test_data["MOCK_URL_HTTPBIN"]
MOCK_URL_EXAMPLE_HTTPS = _test_data["MOCK_URL_EXAMPLE_HTTPS"]
MOCK_URL_EXAMPLE = _test_data["MOCK_URL_EXAMPLE"]
MOCK_URL_EXAMPLE_SIGNED = _test_data["MOCK_URL_EXAMPLE_SIGNED"]
MOCK_URL_GCS_ARCHIVE = _test_data["MOCK_URL_GCS_ARCHIVE"]
MOCK_URL_JIRA_BROWSE_2 = _test_data["MOCK_URL_JIRA_BROWSE_2"]
MOCK_URL_FTP_INVALID = _test_data["MOCK_URL_FTP_INVALID"]
MOCK_URL_PROXY_SHORT = _test_data["MOCK_URL_PROXY_SHORT"]
MOCK_URL_TEST_BASE = _test_data["MOCK_URL_TEST_BASE"]
MOCK_URL_HTTP_A = _test_data["MOCK_URL_HTTP_A"]
MOCK_URL_HTTP_B = _test_data["MOCK_URL_HTTP_B"]
MOCK_URL_MONGODB_MYDB = _test_data["MOCK_URL_MONGODB_MYDB"]
MOCK_URL_MONGODB_MYHOST = _test_data["MOCK_URL_MONGODB_MYHOST"]
MOCK_URL_MONGODB_SIM = _test_data["MOCK_URL_MONGODB_SIM"]

# ── Mock IP addresses ─────────────────────────────────────────────────────────
MOCK_IP_LOCALHOST = _test_data["MOCK_IP_LOCALHOST"]
MOCK_IP_PRIVATE_1 = _test_data["MOCK_IP_PRIVATE_1"]
MOCK_IP_PRIVATE_2 = _test_data["MOCK_IP_PRIVATE_2"]
MOCK_IP_PRIVATE_3 = _test_data["MOCK_IP_PRIVATE_3"]
MOCK_IP_INTERNAL = _test_data["MOCK_IP_INTERNAL"]
MOCK_IP_BIND_ALL = _test_data["MOCK_IP_BIND_ALL"]
MOCK_IP_PUBLIC_1 = _test_data["MOCK_IP_PUBLIC_1"]
MOCK_IP_PUBLIC_2 = _test_data["MOCK_IP_PUBLIC_2"]
MOCK_IP_PUBLIC_3 = _test_data["MOCK_IP_PUBLIC_3"]
MOCK_IP_TEST_1 = _test_data["MOCK_IP_TEST_1"]
MOCK_IP_TEST_3 = _test_data["MOCK_IP_TEST_3"]
MOCK_IP_TEST_4 = _test_data["MOCK_IP_TEST_4"]
MOCK_IP_RANDOM = _test_data["MOCK_IP_RANDOM"]
MOCK_IP_FORWARDED = _test_data["MOCK_IP_FORWARDED"]
MOCK_IP_FORWARDED_TEST = _test_data["MOCK_IP_FORWARDED_TEST"]

# ── Mock file paths ───────────────────────────────────────────────────────────
MOCK_PATH_UPLOADS = _test_data["MOCK_PATH_UPLOADS"]
MOCK_PATH_STORAGE = _test_data["MOCK_PATH_STORAGE"]
MOCK_PATH_CERT_CACHE = _test_data["MOCK_PATH_CERT_CACHE"]
MOCK_PATH_CONFIG = _test_data["MOCK_PATH_CONFIG"]
MOCK_PATH_ERROR_LOG = _test_data["MOCK_PATH_ERROR_LOG"]

# ── Mock GCS (gs://) URLs ────────────────────────────────────────────────────
MOCK_GCS_CERT_PEM = _test_data["MOCK_GCS_CERT_PEM"]
MOCK_GCS_KEY_PEM = _test_data["MOCK_GCS_KEY_PEM"]
MOCK_GCS_CA_PEM = _test_data["MOCK_GCS_CA_PEM"]
MOCK_GCS_PATH_FILE = _test_data["MOCK_GCS_PATH_FILE"]
MOCK_GCS_PATH_TO_FILE = _test_data["MOCK_GCS_PATH_TO_FILE"]
MOCK_GCS_ERROR_LOG = _test_data["MOCK_GCS_ERROR_LOG"]
MOCK_GCS_TEST_BUCKET_PREFIX = _test_data["MOCK_GCS_TEST_BUCKET_PREFIX"]
MOCK_GCS_FILE_JSON = _test_data["MOCK_GCS_FILE_JSON"]
MOCK_GCS_FILE = _test_data["MOCK_GCS_FILE"]
MOCK_GCS_BUCKET_NAME_FILE = _test_data["MOCK_GCS_BUCKET_NAME_FILE"]


async def empty_async_gen():
    """Async generator that yields nothing.

    Use in place of the ``if False: yield`` idiom which SonarQube flags
    as a constant condition.
    """
    for _ in []:
        yield
